create table HSL_QUANTIZATION (
    data ARRAY<ROW<ID STRING,TYPE STRING,FH_ID STRING,ENTRUST_ID BIGINT,RS_TYPE STRING,WORKER_ID STRING,DEPT_NUMBER STRING,DETAIL_CONTENT STRING,SCORE BIGINT,CREATE_ID STRING,CREATE_DATE STRING,UPDATE_ID STRING,UPDATE_DATE STRING,BI_DATE STRING>>,
    database  STRING,
    es  BIGINT,
    id  BIGINT,
    isDdl  BOOLEAN,
    mysqlType  ROW<ID STRING,TYPE STRING,FH_ID STRING,ENTRUST_ID BIGINT,RS_TYPE STRING,WORKER_ID STRING,DEPT_NUMBER STRING,DETAIL_CONTENT STRING,SCORE BIGINT,CREATE_ID STRING,CREATE_DATE STRING,UPDATE_ID STRING,UPDATE_DATE STRING,BI_DATE STRING>,
    `old`  ARRAY<ROW<ID STRING,TYPE STRING,FH_ID STRING,ENTRUST_ID BIGINT,RS_TYPE STRING,WORKER_ID STRING,DEPT_NUMBER STRING,DETAIL_CONTENT STRING,SCORE BIGINT,CREATE_ID STRING,CREATE_DATE STRING,UPDATE_ID STRING,UPDATE_DATE STRING,BI_DATE STRING>>,
    pkNames  ARRAY<STRING>,
    `sql`  STRING,
    `sqlType`    ROW<ID BIGINT,TYPE BIGINT,FH_ID BIGINT,ENTRUST_ID BIGINT,RS_TYPE BIGINT,WORKER_ID BIGINT,DEPT_NUMBER BIGINT,DETAIL_CONTENT BIGINT,SCORE BIGINT,CREATE_ID BIGINT,CREATE_DATE BIGINT,UPDATE_ID BIGINT,UPDATE_DATE BIGINT,BI_DATE BIGINT>,
    `table`  STRING,
    ts  BIGINT,
    `type`  STRING
)
with  (
    'connector' = 'kafka',
    'topic' = 'jjsesf_online-HSL_QUANTIZATION',
    'properties.bootstrap.servers' = '192.168.132.100:9093,192.168.132.102:9093,192.168.132.103:9093',
    'properties.group.id' = 'jjsesf_online-HSL_QUANTIZATION_online',
    'scan.startup.mode' = 'group-offsets',
    'format' = 'json',
    'json.fail-on-missing-field' = 'false',
    'json.ignore-parse-errors' = 'true',
    'properties.zookeeper.connect' = '192.168.132.2:2181,192.168.132.3:2181,192.168.132.4:2181/kafka2'
);